---
- hosts: localhost
  vars:
    epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    epel_repofile_path: "/etc/yum.repos.d/epel.repo"
    pip_packages: ["f5-sdk", "bigsuds", "netaddr", "deepdiff"]

  tasks:
  - name: "Check for instaled EPEL"
    stat: path={{ epel_repofile_path }}
    register: epel_repofile

  - name: "Install EPEL to provide PIP"
    yum:
      name: "{{ epel_repo_url }}"
      state: present
    when: not epel_repofile.stat.exists

  - name: "Import EPEL GPG key"
    rpm_key:
      key: "{{ epel_repo_gpg_key_url }}"
      state: present
    when: not epel_repofile.stat.exists

  - name: "Install pip if not present"
    yum:
      name: python2-pip
      state: latest

  - name: "Update pip and setuptools (required for some pip packages)"
    command: "pip install {{ item }} --upgrade"
    with_items:
      - pip
      - setuptools

  - name: "Install pip packages"
    pip:
      name: "{{ item }}"
      state: present
    with_items: "{{ pip_packages }}"
...
